version: '3.4'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    ports:
      - "8081:443" 
    build:
      context: .
      dockerfile: UserService/Dockerfile

  foodservice:
    image: ${DOCKER_REGISTRY-}foodservice
    ports:
      - "8082:443" 
    build:
      context: .
      dockerfile: FoodService/Dockerfile


  courierservice:
    image: ${DOCKER_REGISTRY-}courierservice
    ports:
      - "8083:443" 
    build:
      context: .
      dockerfile: CourierService/Dockerfile


  librarydata:
    image: ${DOCKER_REGISTRY-}librarydata
    build:
      context: .
      dockerfile: LibraryData/Dockerfile

