version: '3.4'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    ports:
      - "8081:443" 
    depends_on:
      - mssql
    build:
      context: .
      dockerfile: UserService/Dockerfile

  foodservice:
    image: ${DOCKER_REGISTRY-}foodservice
    ports:
      - "8082:443" 
    depends_on:
      - mssql
    build:
      context: .
      dockerfile: FoodService/Dockerfile


  courierservice:
    image: ${DOCKER_REGISTRY-}courierservice
    ports:
      - "8083:443" 
    depends_on:
      - mssql
    build:
      context: .
      dockerfile: CourierService/Dockerfile


  librarydata:
    image: ${DOCKER_REGISTRY-}librarydata
    build:
      context: .
      dockerfile: LibraryData/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Kosongkan@Saja"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer